export const serviceModel = {
    active: true,
    amountTour: 0,
    dateCreation: { currentTime: new Date().toLocaleString() },
    description: "",
    id: null,
    idEnterprise: 0,
    name: "",
    responsible: "",
    typeTour: "",
    userCreation: "",
    value: "",
    initDate: "",
    finalDate: "",
    pickupCustomer: false,
    place: "",
    mon: false,
    tue: false,
    wed: false,
    thu: false,
    fri: false,
    sat: false,
    sun: false,
    city: "",
    feedbacks: {},
    orders: {},
    empresa: {},
    images: {},
    typeRelation: {},
  };