export const serviceModel = {
  active: true,
  dateCreation: { currentTime: new Date().toLocaleString() },
  description: "",
  id: null,
  idEnterprise: 0,
  name: "",
  responsible: "",
  type_tour: "",
  userCreation: "",
  value: 0.00,
  initDate: "",
  finalDate: "",
  pickup_customer: false,
  place: "",
  mon: true,
  tue: true,
  wed: true,
  thu: true,
  fri: true,
  sat: true,
  sun: true,
  city: "",
  feedbacks: {},
  orders: {},
  empresa: {},
  images: {},
  typeRelation: {},
};